image: ruby:2.4.4
pipelines:
  default:
    - step:
        name: 'Test'
        script:
          - bundle install --path vendor/bundle
          - bundle exec rspec
    - step:
        name: 'Quality'
        script:
          - bundle install --path vendor/bundle
          - bundle exec rubocop

definitions:
  caches:
    bundler: vendor/bundle
